if (!window.PDoc) window.PDoc = {};
PDoc.elements = {
  'WysiHat.Commands': { 'name': 'WysiHat.Commands', 'type': 'mixin', 'path': 'wysihat/wysihat/commands.html' },
'WysiHat.Commands#boldSelection': { 'name': 'WysiHat.Commands#boldSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#boldselection-instance_method' },
'WysiHat.Commands#underlineSelection': { 'name': 'WysiHat.Commands#underlineSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#underlineselection-instance_method' },
'WysiHat.Commands#italicSelection': { 'name': 'WysiHat.Commands#italicSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#italicselection-instance_method' },
'WysiHat.Commands#italicSelection': { 'name': 'WysiHat.Commands#italicSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#italicselection-instance_method' },
'WysiHat.Commands#italicSelection': { 'name': 'WysiHat.Commands#italicSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#italicselection-instance_method' },
'WysiHat.Commands#colorSelection': { 'name': 'WysiHat.Commands#colorSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#colorselection-instance_method' },
'WysiHat.Commands#linkSelection': { 'name': 'WysiHat.Commands#linkSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#linkselection-instance_method' },
'WysiHat.Commands#insertOrderedList': { 'name': 'WysiHat.Commands#insertOrderedList', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#insertorderedlist-instance_method' },
'WysiHat.Commands#insertUnorderedList': { 'name': 'WysiHat.Commands#insertUnorderedList', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#insertunorderedlist-instance_method' },
'WysiHat.Commands#insertImage': { 'name': 'WysiHat.Commands#insertImage', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#insertimage-instance_method' },
'WysiHat.Commands#insertHTML': { 'name': 'WysiHat.Commands#insertHTML', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#inserthtml-instance_method' },
'WysiHat.Commands#execCommand': { 'name': 'WysiHat.Commands#execCommand', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#execcommand-instance_method' },
'WysiHat.Commands#queryCommandState': { 'name': 'WysiHat.Commands#queryCommandState', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#querycommandstate-instance_method' },
'WysiHat.Editable': { 'name': 'WysiHat.Editable', 'type': 'namespace', 'path': 'wysihat/wysihat/editable.html' },
'WysiHat.Editable.Methods': { 'name': 'WysiHat.Editable.Methods', 'type': 'namespace', 'path': 'wysihat/wysihat/editable/methods.html' },
'WysiHat.Editor': { 'name': 'WysiHat.Editor', 'type': 'namespace', 'path': 'wysihat/wysihat/editor.html' },
'WysiHat.Editor.attach': { 'name': 'WysiHat.Editor.attach', 'type': 'class method', 'path': 'wysihat/wysihat/editor.html#attach-class_method' },
'String': { 'name': 'String', 'type': 'class', 'path': 'wysihat/string.html' },
'String#formatHTMLOutput': { 'name': 'String#formatHTMLOutput', 'type': 'instance method', 'path': 'wysihat/string.html#formathtmloutput-instance_method' },
'String#formatHTMLInput': { 'name': 'String#formatHTMLInput', 'type': 'instance method', 'path': 'wysihat/string.html#formathtmlinput-instance_method' },
'String#tidyXHTML': { 'name': 'String#tidyXHTML', 'type': 'instance method', 'path': 'wysihat/string.html#tidyxhtml-instance_method' },
'WysiHat.iFrame': { 'name': 'WysiHat.iFrame', 'type': 'namespace', 'path': 'wysihat/wysihat/iframe.html' },
'WysiHat.iFrame.Methods': { 'name': 'WysiHat.iFrame.Methods', 'type': 'namespace', 'path': 'wysihat/wysihat/iframe/methods.html' },
'WysiHat.iFrame.Methods#setStyle': { 'name': 'WysiHat.iFrame.Methods#setStyle', 'type': 'instance method', 'path': 'wysihat/wysihat/iframe/methods.html#setstyle-instance_method' },
'WysiHat.Persistence': { 'name': 'WysiHat.Persistence', 'type': 'mixin', 'path': 'wysihat/wysihat/persistence.html' },
'WysiHat.Persistence#outputFilter': { 'name': 'WysiHat.Persistence#outputFilter', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#outputfilter-instance_method' },
'WysiHat.Persistence#inputFilter': { 'name': 'WysiHat.Persistence#inputFilter', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#inputfilter-instance_method' },
'WysiHat.Persistence#content': { 'name': 'WysiHat.Persistence#content', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#content-instance_method' },
'WysiHat.Persistence#setContent': { 'name': 'WysiHat.Persistence#setContent', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#setcontent-instance_method' },
'WysiHat.Persistence#save': { 'name': 'WysiHat.Persistence#save', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#save-instance_method' },
'WysiHat.Persistence#load': { 'name': 'WysiHat.Persistence#load', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#load-instance_method' },
'WysiHat.Persistence#reload': { 'name': 'WysiHat.Persistence#reload', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#reload-instance_method' },
'Range': { 'name': 'Range', 'type': 'class', 'path': 'wysihat/range.html' },
'String': { 'name': 'String', 'type': 'class', 'path': 'wysihat/string.html' },
'String#sanitize': { 'name': 'String#sanitize', 'type': 'instance method', 'path': 'wysihat/string.html#sanitize-instance_method' },
'Element': { 'name': 'Element', 'type': 'class', 'path': 'wysihat/element.html' },
'Element#sanitize': { 'name': 'Element#sanitize', 'type': 'instance method', 'path': 'wysihat/element.html#sanitize-instance_method' },
'WysiHat.Selection': { 'name': 'WysiHat.Selection', 'type': 'class', 'path': 'wysihat/wysihat/selection.html' },
'new WysiHat.Selection': { 'name': 'new WysiHat.Selection', 'type': 'constructor', 'path': 'wysihat/wysihat/selection.html#new-constructor' },
'WysiHat.Selection#getSelection': { 'name': 'WysiHat.Selection#getSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/selection.html#getselection-instance_method' },
'WysiHat.Selection#getRange': { 'name': 'WysiHat.Selection#getRange', 'type': 'instance method', 'path': 'wysihat/wysihat/selection.html#getrange-instance_method' },
'WysiHat.Selection#selectNode': { 'name': 'WysiHat.Selection#selectNode', 'type': 'instance method', 'path': 'wysihat/wysihat/selection.html#selectnode-instance_method' },
'WysiHat.Selection#getNode': { 'name': 'WysiHat.Selection#getNode', 'type': 'instance method', 'path': 'wysihat/wysihat/selection.html#getnode-instance_method' },
'WysiHat.Toolbar': { 'name': 'WysiHat.Toolbar', 'type': 'class', 'path': 'wysihat/wysihat/toolbar.html' },
'new WysiHat.Toolbar': { 'name': 'new WysiHat.Toolbar', 'type': 'constructor', 'path': 'wysihat/wysihat/toolbar.html#new-constructor' },
'WysiHat.Toolbar#addButtonSet': { 'name': 'WysiHat.Toolbar#addButtonSet', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#addbuttonset-instance_method' },
'WysiHat.Toolbar#addButton': { 'name': 'WysiHat.Toolbar#addButton', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#addbutton-instance_method' },
'WysiHat.Toolbar#observeButtonClick': { 'name': 'WysiHat.Toolbar#observeButtonClick', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#observebuttonclick-instance_method' },
'WysiHat.Toolbar#observeStateChanges': { 'name': 'WysiHat.Toolbar#observeStateChanges', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#observestatechanges-instance_method' },
'WysiHat.Toolbar#mouseDown': { 'name': 'WysiHat.Toolbar#mouseDown', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#mousedown-instance_method' },
'WysiHat.Toolbar#mouseDown': { 'name': 'WysiHat.Toolbar#mouseDown', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#mousedown-instance_method' },
'WysiHat.Toolbar.ButtonSets.Basic': { 'name': 'WysiHat.Toolbar.ButtonSets.Basic', 'type': 'constant', 'path': 'wysihat/wysihat/toolbar/buttonsets.html#basic-constant' },
'WysiHat.Window': { 'name': 'WysiHat.Window', 'type': 'mixin', 'path': 'wysihat/wysihat/window.html' },
'WysiHat.Window#getDocument': { 'name': 'WysiHat.Window#getDocument', 'type': 'instance method', 'path': 'wysihat/wysihat/window.html#getdocument-instance_method' },
'WysiHat.Window#getWindow': { 'name': 'WysiHat.Window#getWindow', 'type': 'instance method', 'path': 'wysihat/wysihat/window.html#getwindow-instance_method' },
'WysiHat.Window#focus': { 'name': 'WysiHat.Window#focus', 'type': 'instance method', 'path': 'wysihat/wysihat/window.html#focus-instance_method' },
'WysiHat.Window#blur': { 'name': 'WysiHat.Window#blur', 'type': 'instance method', 'path': 'wysihat/wysihat/window.html#blur-instance_method' },
'wysihat': { 'name': 'wysihat', 'type': 'section', 'path': 'wysihat.html#wysihat-section' },
'WysiHat': { 'name': 'WysiHat', 'type': 'namespace', 'path': 'wysihat/wysihat.html' }
};